"""Visualization stages V1 and V4: static episode figures and the aggregate dashboard.

Matplotlib only, no seaborn, no network access. Every figure is regenerated by
`scripts/make_figures.py` so nothing in the report is hand-made.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

from social_collusion.env.claims import to_text  # noqa: E402
from social_collusion.env.enums import Role, TruthLabel  # noqa: E402
from social_collusion.env.state import DEAD, GameState  # noqa: E402

LABEL_COLOR = {
    "TRUE": "#2e7d32",
    "FALSE": "#c62828",
    "UNSUPPORTED": "#ef6c00",
    "CONTRADICTORY": "#6a1b9a",
    "AMBIGUOUS": "#546e7a",
}
ROLE_COLOR = {"CREW": "#1565c0", "COALITION": "#c62828"}


def _room_layout(cfg) -> dict[int, tuple[float, float]]:
    """Hub in the middle, leaves around it - deterministic so figures are comparable."""
    n = cfg.n_rooms
    pos = {0: (0.0, 0.0)}
    leaves = [r for r in range(n) if r != 0]
    for k, r in enumerate(leaves):
        ang = 2 * np.pi * k / max(1, len(leaves)) + np.pi / 2
        pos[r] = (float(np.cos(ang)), float(np.sin(ang)))
    return pos


def plot_episode(state: GameState, path: str | Path, privileged: bool = True) -> Path:
    """V1: the map per turn, movement, and the meeting transcript beneath."""
    cfg = state.config
    T = state.horizon + 1
    layout = _room_layout(cfg)
    fig = plt.figure(figsize=(2.1 * T, 7.2))
    gs = fig.add_gridspec(2, T, height_ratios=[1.15, 1.0], hspace=0.28)

    for t in range(T):
        ax = fig.add_subplot(gs[0, t])
        ax.set_xlim(-1.6, 1.6)
        ax.set_ylim(-1.6, 1.6)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_title(f"t{t}", fontsize=10)
        for a, b in cfg.edges:
            ia, ib = cfg.rooms.index(a), cfg.rooms.index(b)
            ax.plot(*zip(layout[ia], layout[ib]), color="#cfd8dc", lw=1.5, zorder=1)
        for r, (x, y) in layout.items():
            marker = state.incident_room == r and state.incident_time >= 0 and t >= state.incident_time
            ax.scatter([x], [y], s=900, facecolor="#ffebee" if marker else "#f5f5f5",
                       edgecolor="#b0bec5", zorder=2)
            ax.text(x, y - 0.36, cfg.rooms[r][:4], ha="center", fontsize=7, color="#607d8b")
        for i in range(cfg.n_agents):
            p = int(state.positions[t, i])
            if p == DEAD:
                continue
            x, y = layout[p]
            k = sum(1 for j in range(i) if int(state.positions[t, j]) == p)
            role = Role(int(state.roles[i])).name
            col = ROLE_COLOR[role] if privileged else "#455a64"
            ax.text(x + 0.34 * np.cos(k * 1.9), y + 0.28 * np.sin(k * 1.9), f"A{i}",
                    ha="center", va="center", fontsize=9, color=col, weight="bold", zorder=3)
        if state.incident_time == t:
            ax.text(0, 1.42, "incident", ha="center", fontsize=8, color="#c62828")
        if state.report_turn == t:
            ax.text(0, -1.5, "report", ha="center", fontsize=8, color="#00695c")

    ax = fig.add_subplot(gs[1, :])
    ax.axis("off")
    names = [f"A{i}" for i in range(cfg.n_agents)]
    lines = []
    for c in state.claims:
        lbl = TruthLabel(c.label).name if c.label is not None else ""
        lines.append((to_text(c, cfg, names), LABEL_COLOR.get(lbl, "#37474f"), lbl if privileged else ""))
    for r in state.responses:
        from social_collusion.env.enums import ResponseType

        tgt = names[r.target] if r.target is not None else ""
        lines.append((f"{names[r.speaker]}: {ResponseType(r.response_type).name} {tgt}", "#37474f", ""))
    votes = ", ".join(
        f"{names[i]}->{'SKIP' if int(state.votes[i]) == cfg.n_agents else names[int(state.votes[i])]}"
        for i in range(cfg.n_agents)
        if state.votes[i] >= 0
    )
    ejected = "nobody" if state.ejected < 0 else names[state.ejected]
    y = 0.98
    for text, col, lbl in lines:
        ax.text(0.01, y, text, fontsize=9, color=col, transform=ax.transAxes, va="top")
        if lbl:
            ax.text(0.80, y, lbl, fontsize=8, color=col, transform=ax.transAxes, va="top")
        y -= 0.075
    ax.text(0.01, y - 0.02, f"votes: {votes}", fontsize=9, transform=ax.transAxes, va="top")
    ax.text(0.01, y - 0.10, f"ejected: {ejected}", fontsize=9, weight="bold",
            transform=ax.transAxes, va="top")
    if privileged and state.incident_creator >= 0:
        ax.text(0.01, y - 0.18,
                f"[privileged] creator {names[state.incident_creator]}, "
                f"victim {names[state.incident_victim]}, "
                f"{cfg.rooms[state.incident_room]} at t{state.incident_time}",
                fontsize=9, color="#c62828", transform=ax.transAxes, va="top")
    return _save(fig, path)


def plot_condition_bars(
    summary: dict[str, dict[str, Any]], metric: str, path: str | Path, title: str = ""
) -> Path:
    """V4: per-condition point estimates with bootstrap CIs across seeds."""
    keys = list(summary)
    vals = [summary[k].get(metric, {}).get("point", np.nan) for k in keys]
    lo = [summary[k].get(metric, {}).get("lo", np.nan) for k in keys]
    hi = [summary[k].get(metric, {}).get("hi", np.nan) for k in keys]
    err = np.array([np.array(vals) - np.array(lo), np.array(hi) - np.array(vals)])
    fig, ax = plt.subplots(figsize=(1.05 * len(keys) + 2.5, 4.0))
    ax.bar(keys, vals, yerr=np.abs(err), capsize=4, color="#1565c0", alpha=0.85)
    ax.set_ylabel(metric.replace("_", " "))
    ax.set_title(title or metric)
    ax.grid(axis="y", alpha=0.3)
    ax.set_ylim(0, max(1.0, float(np.nanmax(hi)) * 1.1))
    return _save(fig, path)


def plot_learning_curves(histories: dict[str, list[dict]], metric: str, path: str | Path) -> Path:
    fig, ax = plt.subplots(figsize=(7, 4.2))
    for name, hist in histories.items():
        x = [h["episodes"] for h in hist]
        y = [h.get(metric, np.nan) for h in hist]
        ax.plot(x, y, label=name, lw=1.6)
    ax.set_xlabel("training episodes")
    ax.set_ylabel(metric.replace("_", " "))
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    return _save(fig, path)


def plot_bandwidth_curve(points: Sequence[tuple[int, float, float, float]], path: str | Path) -> Path:
    """K (0, 2, 4, 8) vs the primary outcome, with CIs - the H3 figure."""
    k = [p[0] for p in points]
    y = [p[1] for p in points]
    lo = [p[2] for p in points]
    hi = [p[3] for p in points]
    fig, ax = plt.subplots(figsize=(5.6, 4.0))
    ax.errorbar(k, y, yerr=[np.array(y) - np.array(lo), np.array(hi) - np.array(y)],
                marker="o", capsize=4, color="#00695c")
    ax.set_xlabel("private channel bandwidth K (0 = no channel)")
    ax.set_ylabel("false-ejection rate")
    ax.grid(alpha=0.3)
    return _save(fig, path)


def plot_symbol_heatmap(semantics: dict[int, dict[str, float]], n_rooms: int, path: str | Path) -> Path:
    """V4: P(sender room | symbol) - the interpretability figure."""
    syms = sorted(semantics)
    m = np.zeros((len(syms), n_rooms))
    for a, s in enumerate(syms):
        for r in range(n_rooms):
            m[a, r] = semantics[s].get(f"p_sender_room_{r}", 0.0)
    fig, ax = plt.subplots(figsize=(1.0 * n_rooms + 2.5, 0.7 * len(syms) + 2.2))
    im = ax.imshow(m, cmap="viridis", vmin=0, vmax=1, aspect="auto")
    ax.set_xticks(range(n_rooms))
    ax.set_yticks(range(len(syms)))
    ax.set_yticklabels([f"symbol {s}" for s in syms])
    ax.set_xlabel("sender's room at the critical moment")
    fig.colorbar(im, ax=ax, label="P(room | symbol)")
    return _save(fig, path)


def plot_counterfactual_effects(effects: dict[str, dict], path: str | Path) -> Path:
    """V3/V4: every intervention's causal effect with its CI, zero line marked."""
    names, pts, los, his = [], [], [], []
    for name, d in effects.items():
        delta = d.get("delta")
        if not isinstance(delta, dict):
            continue
        names.append(name)
        pts.append(delta["point"])
        los.append(delta["lo"])
        his.append(delta["hi"])
    if not names:
        fig, ax = plt.subplots(figsize=(5, 2))
        ax.text(0.5, 0.5, "no counterfactual results", ha="center")
        ax.axis("off")
        return _save(fig, path)
    order = np.argsort(pts)
    names = [names[i] for i in order]
    pts, los, his = np.array(pts)[order], np.array(los)[order], np.array(his)[order]
    fig, ax = plt.subplots(figsize=(7.2, 0.5 * len(names) + 2.2))
    ax.errorbar(pts, range(len(names)), xerr=[pts - los, his - pts], fmt="o",
                capsize=4, color="#4527a0")
    ax.axvline(0, color="#c62828", lw=1.2, ls="--")
    ax.set_yticks(range(len(names)))
    ax.set_yticklabels(names, fontsize=9)
    ax.set_xlabel("causal effect on the primary outcome (actual - control)")
    ax.grid(axis="x", alpha=0.3)
    return _save(fig, path)


def plot_cross_play(matrix: np.ndarray, path: str | Path, title: str = "cross-play") -> Path:
    fig, ax = plt.subplots(figsize=(1.0 * max(matrix.shape[1], 1) + 2.5, 1.0 * max(matrix.shape[0], 1) + 2.2))
    im = ax.imshow(matrix, cmap="magma", aspect="auto")
    ax.set_xlabel("crew policy (seed)")
    ax.set_ylabel("coalition policy (seed)")
    ax.set_title(title)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if np.isfinite(matrix[i, j]):
                ax.text(j, i, f"{matrix[i, j]:.2f}", ha="center", va="center",
                        fontsize=8, color="white")
    fig.colorbar(im, ax=ax)
    return _save(fig, path)


def plot_role_specialization(spec: dict[str, float], keys: Sequence[str], path: str | Path) -> Path:
    creator = [spec.get(f"creator_{k}", 0.0) for k in keys]
    partner = [spec.get(f"partner_{k}", 0.0) for k in keys]
    x = np.arange(len(keys))
    fig, ax = plt.subplots(figsize=(1.15 * len(keys) + 2.5, 4.0))
    ax.bar(x - 0.2, creator, 0.4, label="incident creator", color="#c62828")
    ax.bar(x + 0.2, partner, 0.4, label="partner", color="#1565c0")
    ax.set_xticks(x)
    ax.set_xticklabels([k.replace("_", "\n") for k in keys], fontsize=8)
    ax.set_ylabel("rate")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    return _save(fig, path)


def _save(fig, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=140, bbox_inches="tight")
    plt.close(fig)
    return path


__all__ = [
    "plot_episode",
    "plot_condition_bars",
    "plot_learning_curves",
    "plot_bandwidth_curve",
    "plot_symbol_heatmap",
    "plot_counterfactual_effects",
    "plot_cross_play",
    "plot_role_specialization",
]
